### Admin
POST {{host}}/users/{{userId}}/profiles/admin
Authorization: Bearer {{token}}

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer
Authorization: Bearer {{token}}

### Participant
POST {{host}}/users/{{userId}}/profiles/participant
Authorization: Bearer {{token}}